### ISSUE TITLE
Inifite loop in when decoding

### ISSUE THREAD

**Issue by bladyjoker** [mlabs-haskell/purescript-aeson#4]
https://github.com/mlabs-haskell/purescript-aeson/blob/5054e03ee14376768071c24d63889bfab8db2667/src/Aeson.purs#L559

**Comment by bladyjoker** [comment]
```
> aes = encodeAeson (Just true :: Maybe Boolean)
> aes 
true

> decodeAeson aes :: (Either JsonDecodeError (Maybe Boolean))
/home/bladyjoker/purescript-aeson/.psci_modules/node_modules/Aeson/index.js:853
            return caseAeson({
            ^

RangeError: Maximum call stack size exceeded
    at decodeAeson (/home/bladyjoker/purescript-aeson/.psci_modules/node_modules/Aeson/index.js:853:13)
    at decodeAeson (/home/bladyjoker/purescript-aeson/.psci_modules/node_modules/Aeson/index.js:855:99)
    at decodeAeson (/home/bladyjoker/purescript-aeson/.psci_modules/node_modules/Aeson/index.js:855:99)
    at decodeAeson (/home/bladyjoker/purescript-aeson/.psci_modules/node_modules/Aeson/index.js:855:99)
    at decodeAeson (/home/bladyjoker/purescript-aeson/.psci_modules/node_modules/Aeson/index.js:855:99)
    at decodeAeson (/home/bladyjoker/purescript-aeson/.psci_modules/node_modules/Aeson/index.js:855:99)
    at decodeAeson (/home/bladyjoker/purescript-aeson/.psci_modules/node_modules/Aeson/index.js:855:99)
    at decodeAeson (/home/bladyjoker/purescript-aeson/.psci_modules/node_modules/Aeson/index.js:855:99)
    at decodeAeson (/home/bladyjoker/purescript-aeson/.psci_modules/node_modules/Aeson/index.js:855:99)
    at decodeAeson (/home/bladyjoker/purescript-aeson/.psci_modules/node_modules/Aeson/index.js:855:99)
```
